# Generated by Django 5.2.17 on 2026-08-17 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0002_attributerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('register', 'Registered'), ('upload', 'File Uploaded'), ('request_access', 'Requested File Access'), ('grant', 'Access Granted'), ('reject', 'Access Rejected'), ('revoke', 'Access Revoked'), ('download', 'File Downloaded'), ('request_attribute', 'Requested Attribute'), ('attribute_set', 'Attribute Set by Admin'), ('attribute_removed', 'Attribute Removed by Admin'), ('attribute_approved', 'Attribute Request Approved'), ('attribute_rejected', 'Attribute Request Rejected')], max_length=30)),
                ('detail', models.CharField(max_length=500)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, help_text='Whose personal activity feed this entry appears on.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
