# Generated by Django 5.2.17 on 2026-08-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mp', '0003_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='accessrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('revoked', 'Revoked')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('register', 'Registered'), ('upload', 'File Uploaded'), ('request_access', 'Requested File Access'), ('grant', 'Access Granted'), ('reject', 'Access Rejected'), ('revoke', 'Access Revoked'), ('download', 'File Downloaded'), ('request_attribute', 'Requested Attribute'), ('attribute_set', 'Attribute Set by Admin'), ('attribute_removed', 'Attribute Removed by Admin'), ('attribute_approved', 'Attribute Request Approved'), ('attribute_rejected', 'Attribute Request Rejected'), ('file_deleted', 'File Deleted')], max_length=30),
        ),
    ]
